version: '3'
services:
  app:
    build: .
    restart: always
    environment:
      - PG_HOST=${PG_HOST}
      - TG_MANI_BOT=${TG_MANI_BOT}
      - PG_USER=${PG_USER}
      - PG_PASS=${PG_PASS}
      - PG_DB=${PG_DB}
    