# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
env:
  PG_HOST: ${{ secrets.PG_HOST }}
  TG_MANI_BOT: ${{ secrets.TG_MANI_BOT }}
  PG_USER: ${{ secrets.PG_USER }}
  PG_PASS: ${{ secrets.PG_PASS }}
  PG_DB: ${{ secrets.PG_DB }}
jobs:
  deploy:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
      
    - name: Deploy Bot
      run: |
          # Add your deployment commands here
          # For example:
          pip install -r requirements.txt
          nohup python src/main.py > nohup.out 2> nohup.err < /dev/null &